#!/bin/sh

tag=redirector-php

case $1 in
  build)
    podman build -t $tag -f Containerfile.dev .
    ;;

  dev)
    podman run --volume ./:/opt/app --env COMPOSER_ALLOW_SUPERUSER=1 -p 8000:8000 -i -t $tag /usr/bin/composer run-script dev
    ;;

  shell)
    podman run --volume ./:/opt/app -i -t $tag /bin/sh
    ;;

  composer)
    shift 1
    podman run --volume ./:/opt/app --env COMPOSER_ALLOW_SUPERUSER=1 -i -t $tag /usr/bin/composer "$@"
    ;;
esac
